### ISSUE TITLE
Unable to execute this code due to IndexError

### ISSUE THREAD

**Issue by gr721085** [doriguzzi/lucid-ddos#1]
Traceback (most recent call last):
  File "/home/kali/lucid-ddos/lucid-ddos-master/lucid_dataset_parser.py", line 706, in <module>
    main(sys.argv)
  File "/home/kali/lucid-ddos/lucid-ddos-master/lucid_dataset_parser.py", line 431, in main
    preprocessed_flows = list(flows_list[0])
IndexError: list index out of range

Kindly help me in resolving this issue. Thank You.

**Comment by doriguzzi** [comment]
Hi,
that error can occur when executing the first step of the traffic pre-processing (see the README). The causes can be the following:
1.  the folder indicated with option --dataset_folder is not correct
2. the folder is correct, but it does not contain any pcap file
3. the folder is correct, but the pcap files do not have the "pcap" extension in their filename

If you have successfully clone the repository, the following command (executed in the root folder) should not return any error:

`python3 lucid_dataset_parser.py --dataset_type SYN2020 --dataset_folder ./sample-dataset/ --packets_per_flow 10 --dataset_id SYN2020 --traffic_type all --time_window 10`

Hope this helps.
