### ISSUE TITLE
Inquiry about Timestamps and DDoS Attack Types in CICDDoS2019 Dataset

### ISSUE THREAD

**Issue by whz11** [doriguzzi/lucid-ddos#11]
Hello,

I hope this message finds you well.  I am currently conducting research on DDoS attacks utilizing the CICDDoS2019 dataset. I have found your work to be immensely informative and beneficial to my ongoing project. I am writing to seek your expertise on a specific aspect of the dataset, as I believe you are the best person to address my question.

In analyzing the dataset, I have observed that the timestamps of packets (accessed through pkt.sniff_timestamp using the pyshark library) do not align with the expected dates as mentioned within the dataset's documentation. Specifically, I expected the timestamps to correspond to the dates when various DDoS attack types were simulated, such as January 12 and March 11 of 2018, but instead, the timestamps appear to originate from December 1, 2018, and other dates.

Notably, I've discovered that December 1, 2018, is the creation date of the .pcap file containing these packets. This observation led me to question if the timestamps in the dataset reflect records post-dating the file creation date or if there is some form of conversion or processing that has resulted in the timestamps not matching the time periods described in the original documentation.

Given the significance of time in distinguishing between different DDoS attack types (as outlined in the original CICDDoS2019 paper), I am curious to understand if this discrepancy stems from a misunderstanding on my part, a characteristic of dataset processing, or a peculiarity of the dataset version I am using.

**Comment by doriguzzi** [comment]
Hi,

sorry for the late reply. I think the dataset's authors did some post-processing, that's why you find mismatching dates.
The best option is to contact them and ask for clarification.
Regarding LUCID, that issue does not represent a problem, as LUCID only considers the IAT between packets, not the actual capture time.
Hope this helps.
Roberto
