### ISSUE TITLE
Implement iptables blocking

### ISSUE THREAD

**Issue by debian-user-france1** [doriguzzi/lucid-ddos#2]
A test:

`Model         TIME(sec) PACKETS SAMPLES DDOS% ACC    ERR    F1     PPV    TPR    FPR    TNR    FNR    Data Source
SYN2020-LUCID     0.022 0001761 0000352 0.497 0.9972 0.0981 0.9971 0.9943 1.0000 0.0056 0.9944 0.0000 10t-10n-SYN2020-dataset-test.hdf5`

It's not able to detect a slowloris attack. The accuracy is 99%..... I'm using a newer tshark version than recommended. Oops my interface would be enp4s0

**Comment by debian-user-france1** [comment]
Something happened while slowloris attack:

```
[sudo] Passwort für france1: 
Prediction on network traffic from:  enp4s0
2022-03-05 21:01:17.062500: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-03-05 21:01:17.080559: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 3001000000 Hz
2022-03-05 21:01:17.080784: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x562150de9260 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-03-05 21:01:17.080846: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
/home/france1/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/france1/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
lucid_cnn.py:412: RuntimeWarning: invalid value encountered in long_scalars
  fnr = fn / (fn + tp)
lucid_cnn.py:413: RuntimeWarning: invalid value encountered in long_scalars
  tpr = tp / (tp + fn)
Model         TIME(sec) PACKETS SAMPLES DDOS% ACC    ERR    F1     PPV    TPR    FPR    TNR    FNR    Data Source
SYN2020-LUCID     0.110 0000817 0000117 0.000 1.0000 0.0000 0.0000 0.0000 00nan 0.0000 1.0000 00nan enp4s0

/home/france1/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/france1/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
lucid_cnn.py:412: RuntimeWarning: invalid value encountered in long_scalars
  fnr = fn / (fn + tp)
lucid_cnn.py:413: RuntimeWarning: invalid value encountered in long_scalars
  tpr = tp / (tp + fn)
Model         TIME(sec) PACKETS SAMPLES DDOS% ACC    ERR    F1     PPV    TPR    FPR    TNR    FNR    Data Source
SYN2020-LUCID     0.025 0001896 0000209 0.000 1.0000 0.0000 0.0000 0.0000 00nan 0.0000 1.0000 00nan enp4s0

```

But.. What's that.

**Comment by debian-user-france1** [comment]
0.166 is the ddos percentage while a slowloris attack is running. Now I begin to understand but it doesn't seem to detect. What's the problem with newer tshark versions?

**Comment by doriguzzi** [comment]
Hello,
sorry for the late reply. LUCID has been design as a DDoS detection system, it does not implement any packet filtering mechanisms. In your case, I would suggest to take the list of malicious IP addresses given by LUCID and used them to configure IPTABLES. You can use the "keys" tuple at line 377 in lucid_cnn.py to obtain the list of malicious source addresses.

Hope this helps.

**Comment by debian-user-france1** [comment]
Ok I got it. Now my problem is that this is not only monitoring incoming traffic but outgoing traffic so the server IP is maked as an attacker. I might be able to exclude that...
Another problem is the size of that file. It's huge instead of only one IP per print() # I used print to see what's in keys.

I'm going to try to implement something..

**Comment by debian-user-france1** [comment]
I ran into a problem pretty quick...
```
f=open("example.txt", "r")
list=f.read()

for i in range(len(list)):
    print(list[i])

print()
print()
print(list[1])
print(list[2])
```

This prints every single character that's in example.txt (the keys file)
Isn't keys an array with tuples in it? I thought I could get the length of the array and then go through every element of the array (so every tuple that's in it) and then get the attacker IP, put the IP into a wordlist or a new array. To prevent false positives I'd have to count in how many tuples the attacker IP is and trigger at like about 50 times.

**Comment by debian-user-france1** [comment]
https://stackoverflow.com/questions/71873752/iterating-through-a-python-array-does-not-work/71874037#71874037

Ok closing now.
