### ISSUE TITLE
Label does not match ground truth?

### ISSUE THREAD

**Issue by abc744587** [doriguzzi/lucid-ddos#6]
Hello,
I used the CICIDS2017 Wednesday Dataset for Traffic pre-processing, but the result does not match the ground truth given by CICIDS2017. Is there any error? Or are there any parameters that need to be adjusted?  Thanks :)

![issue](https://user-images.githubusercontent.com/85470040/186932053-5a9d06dc-2f5c-4d21-9bd5-423250a58643.png)
**▲I analyze the DDoS attack period.**

![image](https://user-images.githubusercontent.com/85470040/186935385-c6139d4b-5e02-48aa-922d-a3033390a544.png)
**▲The PCAP file for this period.**

![image](https://user-images.githubusercontent.com/85470040/186935178-43152cf1-2309-4f1f-b684-02c037c02b13.png)
**▲Results of Traffic pre-processing first step.**

![image](https://user-images.githubusercontent.com/85470040/186935479-9eef3986-a2b3-43f8-a619-a3366e5e1755.png)
**▲The sum of DoS attacks was 252,661.**

**Comment by abc744587** [comment]
**Hello,**
**The last picture is calculated from the Label field in the csv file provided by CIC-IDS2017, this is Flows.**
![issues_Total](https://user-images.githubusercontent.com/85470040/189471146-c2d7733d-26bc-48ab-b34f-74c041c0269c.PNG)

**Are you checking "DDoS LOIT (15:56 – 16:16)" on Friday afternoon?
Will the parsed Flows match the Labels of the csv file?**

![issues_Friday DDoS](https://user-images.githubusercontent.com/85470040/189471153-d6e79e3b-0762-4055-9232-96faffa442d6.PNG)

**Thank you very much for taking the time to reply.**

--Ren

**Comment by abc744587** [comment]
Hello,

I split the pcap of Friday "DDoS LOIT (15:56 – 16:16)" and labeled it.

But the result does not match the Label of the csv file?

![image](https://user-images.githubusercontent.com/85470040/189524320-c48d47bd-6aec-487d-9ab8-e0c1ceda3abb.png)
**▲DDoS Label results for csv**

![image](https://user-images.githubusercontent.com/85470040/189524411-2a6640a4-6f39-4f78-977a-9455aa116c4b.png)
**▲DDoS Label results**

In addition, I would like to ask whether the results should be based on flows or fragments?


Thanks for taking the time to read.


--Ren

**Comment by doriguzzi** [comment]
Hi,

for the first question: yes, I used the attack called by the authors of the dataset "DDoS LOIT (15:56 – 16:16)" collected on Friday afternoon. 
For the second question: yes, the file with the labels of such an attack is "Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv.

You are right,  the number of flows in the csv files and the number of flows extracted by the LUCID parser do not match. The reason is very simple, in the csv file there are pairs of flows with the same label (see attached figure), i.e., different flows generated at different times (this is speculation, as the timestamp in the csv is not precise enough), which have the same source/dest IPs, source/dest ports and protocol.
LUCID considers these flows as the same flow, which is why you get a lower number of flows with LUCID.

Hope this clarifies.

--roberto

![image](https://user-images.githubusercontent.com/1794129/194822599-b7e258e5-2bce-4a10-ba20-d659158de33e.png)

**Comment by LailaAfreen** [comment]
Hello @abc744587,

I too have been trying to use the CIC-IDS2017 dataset and have found that in the labelling stage, the number of DDoS labelled flows/fragments are 0. 

I tried looking at the pcap file for the timeframe for "DDoS LOIT (15:56 – 16:16)" but have found no address, 172.16.0.1 and I can see that due to this, it may be that there is no labelling of DDoS traffic. 

I noticed that for the preprocessing step, you have split the time window to 2 minute chunks . However, I have used the pcap for the entire time window: 15:56 – 16:16. Any suggestions?

**Comment by LailaAfreen** [comment]
I would also like to add that i filtered the original pcap file with time window: 15:56 – 16:16 and found no IP address 172.16.0.1 on further filtering. Is there something wrong with my approach?

**Comment by LailaAfreen** [comment]
> Hi,
> 
> for the first question: yes, I used the attack called by the authors of the dataset "DDoS LOIT (15:56 – 16:16)" collected on Friday afternoon. For the second question: yes, the file with the labels of such an attack is "Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv.
> 
> You are right, the number of flows in the csv files and the number of flows extracted by the LUCID parser do not match. The reason is very simple, in the csv file there are pairs of flows with the same label (see attached figure), i.e., different flows generated at different times (this is speculation, as the timestamp in the csv is not precise enough), which have the same source/dest IPs, source/dest ports and protocol. LUCID considers these flows as the same flow, which is why you get a lower number of flows with LUCID.
> 
> Hope this clarifies.
> 
> --roberto
> 
> ![image](https://user-images.githubusercontent.com/1794129/194822599-b7e258e5-2bce-4a10-ba20-d659158de33e.png)

Hi @doriguzzi,

Could you please tell me where you found this csv file from? 


I downloaded the datasheet zip file (see below):
![csv file](https://user-images.githubusercontent.com/109215309/235364695-4cb0f275-ae9d-4277-a0db-4c4ee3e228ff.png)
and opened the file shown by Ren. but do not see any source or destination addresses but only destination port as shown below:
<img width="646" alt="Capture" src="https://user-images.githubusercontent.com/109215309/235364865-0367e0e5-1817-482f-b42f-2dfec96ad23f.PNG">

Any idea where i am going wrong?

**Comment by abc744587** [comment]
Hi @LailaAfreen ,


Are you saying that you filtered the traffic range of "**DDoS LOIT (15:56-16:16)**" in Wireshark but did not find 172.16.0.1?

If so, you must pay attention to the adjustment of your time zone and the "**Time Display Format**" option in Wireshark. You can try selecting the option shown in the picture. Although I said that I used the interval of "15:56-16:16" for filtering, actually I guess it is because of my time zone, so in my pcap file it shows as "14:56-15:16".

![image](https://user-images.githubusercontent.com/85470040/235364664-c5f818b9-85a8-4bad-b65a-0827b041733b.png)

![image](https://user-images.githubusercontent.com/85470040/235365057-c620f27d-2a33-4113-88f6-5910aef6d07c.png)

Also, the CSV file in the author's figure should be the CSV file inside the 'GeneratedLabelledFlows.zip'.


-Ren

**Comment by LailaAfreen** [comment]
> Hi @LailaAfreen ,
> 
> Are you saying that you filtered the traffic range of "**DDoS LOIT (15:56-16:16)**" in Wireshark but did not find 172.16.0.1?
> 
> If so, you must pay attention to the adjustment of your time zone and the "**Time Display Format**" option in Wireshark. You can try selecting the option shown in the picture. Although I said that I used the interval of "15:56-16:16" for filtering, actually I guess it is because of my time zone, so in my pcap file it shows as "14:56-15:16".
> 
> ![image](https://user-images.githubusercontent.com/85470040/235364664-c5f818b9-85a8-4bad-b65a-0827b041733b.png)
> 
> ![image](https://user-images.githubusercontent.com/85470040/235365057-c620f27d-2a33-4113-88f6-5910aef6d07c.png)
> 
> Also, the CSV file in the author's figure should be the CSV file inside the 'GeneratedLabelledFlows.zip'.
> 
> -Ren

Hi @abc744587,

Thanks for your quick response and the brilliant suggestion for adjusting the time zone. I finally found the time window between 20:56 - 21:16. Additionally, I found the relevant csv files right after writing to both of you. Your help is much appreciated.

-Laila
