### ISSUE TITLE
Difficulty Improving F1 Score, Accuracy, and Decreasing FPR

### ISSUE THREAD

**Issue by real-noob** [doriguzzi/lucid-ddos#8]
Hey there,

I've been working on implementing your model in my Desktop environment following the steps provided in the description. However, I'm encountering some challenges in improving the performance metrics. Here are the details:

1. Current Metrics:
   - F1 Score: 0.8146
   - Accuracy: 0.7697
   - FPR (False Positive Rate): 0.4615

2. Steps Taken:
   - I've used epochs 1000, 1500, 2000, and 2500 during training.
   - I also tried Cross Validation with 2, 3, 5, and 7 folds.
   - The dataset used is [UNB's CIC-DDoS2019].

3. Prediction Output:
   "'_{Model': 'SYN2020-LUCID',
   'Time': '0.193',
   'Packets': 8907,
   'Samples': 5240,
   'DDOS%': '0.731',
   'Accuracy': '0.7697',
   'F1Score': '0.8136',
   'TPR': '0.9966',
   'FPR': '0.4615',
   'TNR': '0.5385',
   'FNR': '0.0034',
   'Source': '10t-10n-IDS201X-dataset-test.hdf5'_}"

4. Approach:
   I would appreciate some guidance on potential approaches to further improve the performance of the model. Specifically, I'm interested in:
   - Increasing the F1 Score beyond 0.8146
   - Improving the Accuracy above 0.7697
   - Reducing the FPR below 0.4615

5. Dataset:
   I used your latest provided datasets ([UNB's CIC-DDoS2019]).

Any insights or suggestions on how to tackle these challenges would be greatly appreciated. Thank you in advance for your help!

**Comment by doriguzzi** [comment]
Hi,

I see in your log that you are using an old model (SYN2020-LUCID) on an old test file. Maybe you still have some old files coming from the previous versions of the code. I suggest you clean up the sample-dataset folder and leave there only the three CIC-DDoS-2019-* pcap files. 
Then, repeat the whole pre-processing/training procedure. You should find a new model named "10t-10n-DOS2019-LUCID.h5" in the "output" folder. Then, test using the command provided in the readme. The output log should be something like:
_{'Model': 'DOS2019-LUCID',
 'Time': '0.015',
 'Packets': 3285,
 'Samples': 749,
 'DDOS%': '0.430',
 'Accuracy': '0.9907',
 'F1Score': '0.9892',
 'TPR': '0.9787',
 'FPR': '0.0000',
 'TNR': '1.0000',
 'FNR': '0.0213',
 'Source': '10t-10n-DOS2019-dataset-test.hdf5'}_

(Please compare the first and the last lines of my output with the first and the last lines of yours)

Hope this helps.

--roberto

**Comment by real-noob** [comment]
is there any way that it could be used for detecting DHCP starvation attacks?
