### ISSUE TITLE
Required time to train the model and detect the live attack. 

### ISSUE THREAD

**Issue by real-noob** [doriguzzi/lucid-ddos#9]
Can u explain the process how can one know the required time to train the model and how can on e know the required time to predict the live attack?

**Comment by real-noob** [comment]
also how can i know the convergence time?

**Comment by doriguzzi** [comment]
> Can u explain the process how can one know the required time to train the model and how can on e know the required time to predict the live attack?

The training and inference times depend on many factors: the machine where you run LUCID, the size of the training set (for the training time), the mini-batch size, the number of convolutional filters, etc.
Nevertheless, LUCID prints both training and inference times, therefore it should be easy for you to check LUCID's performance with your dataset on your hardware.

**Comment by doriguzzi** [comment]
> also how can i know the convergence time?

In the current code, LUCID does not measure the training time. However, you can easily measure such a time by using the time.time() method in this way:
`start = time.time()`
`rnd_search_cv.fit(X_train, Y_train, epochs=args.epochs, validation_data=(X_val, Y_val), callbacks=[es, mc])`
`stop = time.time()`
`print ("Training time: ", stop-start)`

where `rnd_search_cv.fit(...)` is the training method you can find on line 167 of `lucid_cnn.py`.

--roberto

**Comment by real-noob** [comment]
and how have u calculated the parameters? ( I have read your article but could not get a solid idea how you obtained that.)
